###Numpy

Numpy fornece um grande conjunto de funções e operações de biblioteca que ajudam os programadores a executar facilmente cálculos numéricos.

- 1D array: axis 0 -> shape (4,)
- 2D array: axis 0 e axis 1 -> shape (2,3)
- 3d array: axis 0, axis 1 e axis 2 -> shape (4,3,2)

Mas em Numpy, as dimensões são chamadas de eixos. O número de eixos ẽ classificado. Em termos mais simples, quando você tem mais de uma matriz unidimensiona, então o conceito do eixo surge. Por exemplo, a matriz 2-D tem 2 eixos.

In [1]:
import numpy as np

In [3]:
#Criar uma matriz
array = np.array([10,20,30,40,50])
array

array([10, 20, 30, 40, 50])

In [4]:
#tipo
type(array)

numpy.ndarray

In [5]:
duas = np.array([[10,9,8,7,6], [5,4,3,2,1]])
duas

array([[10,  9,  8,  7,  6],
       [ 5,  4,  3,  2,  1]])

In [8]:
tres = np.array([
    [15,14,13,12,11],
    [10,9,8,7,6],
    [5,4,3,2,1]
])
tres

array([[15, 14, 13, 12, 11],
       [10,  9,  8,  7,  6],
       [ 5,  4,  3,  2,  1]])

In [9]:
#Experimento de processamento
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [10]:
#Acessar os arrays
array[0]

np.int64(10)

In [11]:
array[-1]

np.int64(50)

In [12]:
#range
array[2:]

array([30, 40, 50])

In [13]:
#Operações
array[0] + array[1]

np.int64(30)

In [14]:
#Operações lógica
array[0] == array[1]

np.False_

In [15]:
#verificar dimensão
array.shape

(5,)

In [16]:
duas.shape

(2, 5)

In [17]:
#loop
for loop in array:
    print(loop)

10
20
30
40
50


In [18]:
for loop in duas:
    print(loop)

[10  9  8  7  6]
[5 4 3 2 1]


In [19]:
for loop in duas:
    for intern in loop:
        print(intern)

10
9
8
7
6
5
4
3
2
1


In [20]:
import pandas as pd

In [26]:
pd.DataFrame(array, columns=['vetor 1D'])

,vetor 1D
0,10
1,20
2,30
3,40
4,50
